FROM golang:1.26.5@sha256:ae5a2316d12f3e78fd99177dad452e6ad4f240af2d71d57b480c3477f250fec6 AS build
ARG MERC_BUILD_VERSION=dev
ARG MERC_BUILD_COMMIT=unknown
ARG MERC_BUILD_DATE=unknown
WORKDIR /src/control
COPY control/go.mod control/go.sum ./
RUN go mod download
COPY control/ ./
COPY ops/healthcheck.c /tmp/healthcheck.c
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath \
    -ldflags="-s -w -X main.controlVersion=${MERC_BUILD_VERSION} -X main.controlCommit=${MERC_BUILD_COMMIT} -X main.controlBuildDate=${MERC_BUILD_DATE}" \
    -o /merc . && \
    cc -static -Os -s -Wall -Wextra -Werror -o /merc-healthcheck /tmp/healthcheck.c

FROM gcr.io/distroless/static:nonroot@sha256:f7f8f729987ad0fdf6b05eeeae94b26e6a0f613bdf46feea7fc40f7bd72953e6
ARG MERC_BUILD_VERSION=dev
ARG MERC_BUILD_COMMIT=unknown
ARG MERC_BUILD_DATE=unknown
LABEL org.opencontainers.image.title="merc control plane" \
      org.opencontainers.image.version="${MERC_BUILD_VERSION}" \
      org.opencontainers.image.revision="${MERC_BUILD_COMMIT}" \
      org.opencontainers.image.created="${MERC_BUILD_DATE}" \
      org.opencontainers.image.source="https://github.com/joshuahickscorp/merc"
WORKDIR /
COPY --from=build /merc /merc
COPY --from=build /merc-healthcheck /merc-healthcheck
COPY web/index.html web/buyer.html web/admin.html /web/
COPY web/favicon.ico /web/favicon.ico
USER nonroot:nonroot
EXPOSE 8080
ENTRYPOINT ["/merc"]
