"""Blender emission: the only module that speaks to Blender.

Turns PartSpec trees and InstancingPlans into editable .blend files, GLB
exports, metrics JSON, and optional EEVEE preview renders via a generated
headless Blender script.
"""

from __future__ import annotations

import json
import os
import subprocess
import textwrap
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from blender_vision.core.config import discover_blender
from blender_vision.core.errors import BackendUnavailable
from blender_vision.core.util import atomic_write_json, atomic_write_text
from blender_vision.procedural.archetype import Archetype, PartSpec
from blender_vision.procedural.instancing import InstancingPlan
from blender_vision.procedural.library import ArchetypeLibrary, default_library
from blender_vision.procedural.lod import LodLevel, filter_parts_for_lod, generate_lods

BLENDER_SCRIPT_TEMPLATE = r'''
# Auto-generated by blender_vision.procedural.emit — do not hand-edit.
import json
import math
import sys
from pathlib import Path

import bpy
from mathutils import Euler, Vector

SPEC_PATH = Path(r"""__SPEC_PATH__""")
spec = json.loads(SPEC_PATH.read_text(encoding="utf-8"))
out = Path(spec["output_dir"])
out.mkdir(parents=True, exist_ok=True)

# --factory-startup already gave us a clean scene; do not re-read home file
# (read_factory_settings can re-trigger Metal GPU init crashes on some hosts).
scene = bpy.context.scene
scene.unit_settings.system = "METRIC"
scene.unit_settings.scale_length = 1.0
for obj in list(bpy.data.objects):
    bpy.data.objects.remove(obj, do_unlink=True)


def ensure_collection(name, parent=None):
    col = bpy.data.collections.get(name)
    if col is None:
        col = bpy.data.collections.new(name)
        if parent is None:
            scene.collection.children.link(col)
        else:
            parent.children.link(col)
    return col


def ensure_material(name):
    mat = bpy.data.materials.get(name)
    if mat is None:
        mat = bpy.data.materials.new(name=name)
        mat.use_nodes = True
        nodes = mat.node_tree.nodes
        bsdf = nodes.get("Principled BSDF")
        if bsdf:
            # Neutral placeholder; inverse-materials subsystem owns real shading.
            colour = {
                "steel": (0.35, 0.37, 0.40, 1),
                "chassis": (0.18, 0.18, 0.20, 1),
                "bezel": (0.12, 0.12, 0.13, 1),
                "vent": (0.08, 0.08, 0.09, 1),
                "metal": (0.55, 0.55, 0.58, 1),
                "drive": (0.22, 0.22, 0.25, 1),
                "gpu": (0.15, 0.25, 0.18, 1),
                "heatsink": (0.45, 0.45, 0.48, 1),
                "connector": (0.05, 0.05, 0.05, 1),
                "led": (0.1, 0.8, 0.2, 1),
                "port": (0.4, 0.55, 0.2, 1),
                "fan": (0.1, 0.1, 0.1, 1),
                "blanking": (0.2, 0.2, 0.22, 1),
                "pdu": (0.1, 0.15, 0.35, 1),
                "outlet": (0.7, 0.7, 0.75, 1),
                "breaker": (0.6, 0.15, 0.1, 1),
                "tray": (0.4, 0.35, 0.2, 1),
                "cable": (0.05, 0.05, 0.05, 1),
                "cooling": (0.7, 0.75, 0.8, 1),
                "louvre": (0.55, 0.6, 0.65, 1),
                "floor": (0.3, 0.3, 0.32, 1),
                "ceiling": (0.85, 0.85, 0.88, 1),
                "grid": (0.5, 0.5, 0.52, 1),
                "wall": (0.75, 0.75, 0.78, 1),
                "concrete": (0.55, 0.55, 0.55, 1),
                "threshold": (0.4, 0.35, 0.3, 1),
                "door": (0.25, 0.28, 0.35, 1),
                "aisle_cold": (0.2, 0.35, 0.55, 1),
                "aisle_hot": (0.55, 0.25, 0.2, 1),
                "guide": (0.9, 0.85, 0.2, 1),
                "volume": (0.5, 0.5, 0.5, 1),
                "junction": (0.35, 0.35, 0.38, 1),
                "structure": (0.45, 0.45, 0.45, 1),
                "containment": (0.6, 0.65, 0.7, 1),
                "glass": (0.7, 0.85, 0.9, 1),
                "seal": (0.1, 0.1, 0.1, 1),
                "panel": (0.3, 0.3, 0.32, 1),
                "baseboard": (0.4, 0.4, 0.42, 1),
                "cornice": (0.7, 0.7, 0.72, 1),
                "status_ok": (0.1, 0.9, 0.2, 1),
                "status_warn": (0.95, 0.75, 0.1, 1),
                "status_fault": (0.95, 0.15, 0.1, 1),
                "status_off": (0.15, 0.15, 0.15, 1),
                "status_maintenance": (0.2, 0.4, 0.9, 1),
                "status_cell": (0.2, 0.8, 0.3, 1),
                "neutral": (0.5, 0.5, 0.5, 1),
            }.get(name, (0.5, 0.5, 0.5, 1))
            bsdf.inputs["Base Color"].default_value = colour
            if name.startswith("status_") or name == "led":
                bsdf.inputs["Emission Color"].default_value = colour
                if "Emission Strength" in bsdf.inputs:
                    bsdf.inputs["Emission Strength"].default_value = 3.0
    return mat


def link_object(obj, collection):
    for col in list(obj.users_collection):
        col.objects.unlink(obj)
    collection.objects.link(obj)


def apply_transform(obj, transform):
    loc = transform.get("location", [0, 0, 0])
    rot = transform.get("rotation_euler", [0, 0, 0])
    scale = transform.get("scale", [1, 1, 1])
    obj.location = Vector(loc)
    obj.rotation_euler = Euler(rot, "XYZ")
    obj.scale = Vector(scale)


def make_box(name, size, collection, material):
    bpy.ops.mesh.primitive_cube_add(size=1.0, location=(0, 0, 0))
    obj = bpy.context.active_object
    obj.name = name
    obj.data.name = name + "_mesh"
    obj.scale = Vector(size)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    if material:
        obj.data.materials.append(ensure_material(material))
    link_object(obj, collection)
    return obj


def make_cylinder(name, size, segments, collection, material):
    # size = (diameter_x, diameter_y, height_z) in local space before object transform
    radius = 0.5 * max(size[0], size[1])
    depth = size[2]
    bpy.ops.mesh.primitive_cylinder_add(
        vertices=max(8, int(segments)),
        radius=radius,
        depth=depth,
        location=(0, 0, 0),
    )
    obj = bpy.context.active_object
    obj.name = name
    obj.data.name = name + "_mesh"
    if material:
        obj.data.materials.append(ensure_material(material))
    link_object(obj, collection)
    return obj


def make_hollow_box(name, size, wall, open_face, collection, material):
    # Outer box minus inner (approx via solidify on open box shell using 5 faces as boxes)
    sx, sy, sz = size
    t = max(wall, 0.001)
    parts = []
    # +X -X walls
    for sign, label in ((1, "px"), (-1, "nx")):
        if open_face in (f"{'+' if sign>0 else '-'}X",):
            continue
        o = make_box(f"{name}_{label}", (t, sy, sz), collection, material)
        o.location.x = sign * (sx * 0.5 - t * 0.5)
        parts.append(o)
    for sign, label in ((1, "py"), (-1, "ny")):
        if open_face in (f"{'+' if sign>0 else '-'}Y",):
            continue
        o = make_box(f"{name}_{label}", (sx, t, sz), collection, material)
        o.location.y = sign * (sy * 0.5 - t * 0.5)
        parts.append(o)
    for sign, label in ((1, "pz"), (-1, "nz")):
        if open_face in (f"{'+' if sign>0 else '-'}Z",):
            continue
        o = make_box(f"{name}_{label}", (sx, sy, t), collection, material)
        o.location.z = sign * (sz * 0.5 - t * 0.5)
        parts.append(o)
    if not parts:
        return make_box(name, size, collection, material)
    # Join walls into one object with semantic name
    bpy.ops.object.select_all(action="DESELECT")
    for o in parts:
        o.select_set(True)
    bpy.context.view_layer.objects.active = parts[0]
    bpy.ops.object.join()
    obj = bpy.context.active_object
    obj.name = name
    obj.data.name = name + "_mesh"
    return obj


def make_vent_field(name, geom, collection, material):
    sx, sy, sz = geom["size"]
    cx = max(1, int(geom.get("count_x", 1)))
    cz = max(1, int(geom.get("count_z", 1)))
    pitch = geom.get("pitch", [sx / cx, 0.0, sz / cz])
    cell = geom.get("cell_size", [pitch[0] * 0.5, sy, pitch[2] * 0.5])
    parts = []
    for iz in range(cz):
        for ix in range(cx):
            x = (ix - (cx - 1) * 0.5) * pitch[0]
            z = (iz - (cz - 1) * 0.5) * pitch[2]
            o = make_box(f"{name}_{ix}_{iz}", cell, collection, material)
            o.location = Vector((x, 0.0, z))
            parts.append(o)
    if not parts:
        return make_box(name, geom["size"], collection, material)
    bpy.ops.object.select_all(action="DESELECT")
    for o in parts:
        o.select_set(True)
    bpy.context.view_layer.objects.active = parts[0]
    bpy.ops.object.join()
    obj = bpy.context.active_object
    obj.name = name
    obj.data.name = name + "_mesh"
    return obj


def make_light_cell(name, geom, collection, material):
    return make_box(name, geom["size"], collection, material)


def make_bundle(name, geom, collection, material):
    # Multi-strand cylinder approximation along local Z
    strands = max(1, int(geom.get("count_x", geom.get("extras", {}).get("strand_count", 6))))
    dia = max(geom["size"][0], geom["size"][1])
    length = geom["size"][2]
    core_r = dia * 0.5
    strand_r = core_r / max(2.5, math.sqrt(strands))
    parts = []
    for i in range(strands):
        ang = 2 * math.pi * i / strands
        r = core_r * 0.45
        bpy.ops.mesh.primitive_cylinder_add(
            vertices=8,
            radius=strand_r,
            depth=length,
            location=(math.cos(ang) * r, math.sin(ang) * r, 0.0),
        )
        o = bpy.context.active_object
        o.name = f"{name}_s{i}"
        if material:
            o.data.materials.append(ensure_material(material))
        link_object(o, collection)
        parts.append(o)
    bpy.ops.object.select_all(action="DESELECT")
    for o in parts:
        o.select_set(True)
    bpy.context.view_layer.objects.active = parts[0]
    bpy.ops.object.join()
    obj = bpy.context.active_object
    obj.name = name
    obj.data.name = name + "_mesh"
    return obj


def build_geometry(name, geom, collection, material):
    kind = geom["kind"]
    if kind == "box" or kind == "panel":
        return make_box(name, geom["size"], collection, material)
    if kind == "cylinder":
        return make_cylinder(name, geom["size"], geom.get("segments", 12), collection, material)
    if kind == "hollow_box":
        return make_hollow_box(
            name, geom["size"], geom.get("wall_thickness", 0.002),
            geom.get("open_face", ""), collection, material,
        )
    if kind == "vent_field":
        return make_vent_field(name, geom, collection, material)
    if kind == "light_cell":
        return make_light_cell(name, geom, collection, material)
    if kind == "bundle" or kind == "tube":
        return make_bundle(name, geom, collection, material)
    return make_box(name, geom["size"], collection, material)


def build_part_tree(part, collection, parent_empty=None):
    geom = part["geometry"]
    obj = build_geometry(part["name"], geom, collection, part.get("material_slot", "neutral"))
    apply_transform(obj, part.get("transform", {}))
    if parent_empty is not None:
        obj.parent = parent_empty
    # State as custom properties (non-geometric)
    for key in part.get("state_keys", []):
        obj[key] = part.get("material_slot", "")
    children_root = obj
    for child in part.get("children", []):
        build_part_tree(child, collection, parent_empty=children_root)
    return obj


def triangle_count(objects):
    total = 0
    for obj in objects:
        if obj.type != "MESH" or obj.data is None:
            continue
        mesh = obj.data
        mesh.calc_loop_triangles()
        total += len(mesh.loop_triangles)
    return total


def world_bbox(objects):
    mins = Vector((1e9, 1e9, 1e9))
    maxs = Vector((-1e9, -1e9, -1e9))
    any_mesh = False
    for obj in objects:
        if obj.type != "MESH":
            continue
        any_mesh = True
        for corner in obj.bound_box:
            w = obj.matrix_world @ Vector(corner)
            mins.x = min(mins.x, w.x); mins.y = min(mins.y, w.y); mins.z = min(mins.z, w.z)
            maxs.x = max(maxs.x, w.x); maxs.y = max(maxs.y, w.y); maxs.z = max(maxs.z, w.z)
    if not any_mesh:
        return [0, 0, 0], [0, 0, 0]
    return list(mins), list(maxs)


metrics = {"prototypes": {}, "instances": 0, "unique_meshes": 0, "renders": []}

# ---- Prototypes (one collection each, mesh data created once) ----
root_col = ensure_collection("ProceduralRoot")
proto_root = ensure_collection("Prototypes", root_col)
instance_root = ensure_collection("Instances", root_col)

prototype_collections = {}
for proto in spec.get("prototypes", []):
    pid = proto["prototype_id"]
    pcol = ensure_collection(pid, proto_root)
    pcol.hide_render = True
    pcol.hide_viewport = True
    for part in proto.get("parts", []):
        build_part_tree(part, pcol)
    objs = [o for o in pcol.objects]
    mins, maxs = world_bbox(objs)
    metrics["prototypes"][pid] = {
        "archetype": proto.get("archetype"),
        "lod": proto.get("lod", "near"),
        "triangle_count": triangle_count(objs),
        "bbox_min": mins,
        "bbox_max": maxs,
        "bbox_size": [maxs[i] - mins[i] for i in range(3)],
        "object_count": len(objs),
        "part_names": [o.name for o in objs],
    }
    prototype_collections[pid] = pcol

metrics["unique_meshes"] = len(prototype_collections)

# ---- Instances as collection instances (linked, not copies) ----
for placement in spec.get("placements", []):
    pid = placement["prototype_id"]
    pcol = prototype_collections.get(pid)
    if pcol is None:
        continue
    inst = bpy.data.objects.new(placement["instance_id"], None)
    inst.instance_type = "COLLECTION"
    inst.instance_collection = pcol
    apply_transform(inst, {
        "location": placement.get("location", [0, 0, 0]),
        "rotation_euler": placement.get("rotation_euler", [0, 0, 0]),
        "scale": placement.get("scale", [1, 1, 1]),
    })
    for k, v in placement.get("state", {}).items():
        inst[k] = v
    link_object(inst, instance_root)
    metrics["instances"] += 1

# Unhide instance root; keep prototypes hidden (instances still draw them)
for pcol in prototype_collections.values():
    pcol.hide_viewport = False  # required for collection instances to draw
    pcol.hide_render = False

# ---- Optional standalone archetype metrics (no placements) ----
for entry in spec.get("archetype_builds", []):
    name = entry["name"]
    lod = entry.get("lod", "near")
    acol = ensure_collection(f"arch_{name}_{lod}", root_col)
    for part in entry.get("parts", []):
        build_part_tree(part, acol)
    objs = [o for o in acol.objects]
    mins, maxs = world_bbox(objs)
    metrics.setdefault("archetypes", {})[f"{name}:{lod}"] = {
        "triangle_count": triangle_count(objs),
        "bbox_min": mins,
        "bbox_max": maxs,
        "bbox_size": [maxs[i] - mins[i] for i in range(3)],
        "object_count": len(objs),
        "part_names": sorted({o.name for o in objs}),
    }

# ---- Save .blend ----
blend_path = out / spec.get("blend_name", "scene.blend")
bpy.ops.wm.save_as_mainfile(filepath=str(blend_path))
metrics["blend_path"] = str(blend_path)
metrics["blend_bytes"] = blend_path.stat().st_size

# ---- Export GLB ----
glb_path = out / spec.get("glb_name", "scene.glb")
# Select all mesh-bearing content for export
bpy.ops.object.select_all(action="SELECT")
bpy.ops.export_scene.gltf(
    filepath=str(glb_path),
    export_format="GLB",
    use_selection=False,
    export_apply=False,
)
metrics["glb_path"] = str(glb_path)
metrics["glb_bytes"] = glb_path.stat().st_size if glb_path.is_file() else 0

# ---- Renders ----
renders = spec.get("renders") or []
if renders:
    # Simple world lighting
    world = bpy.data.worlds.new("World")
    scene.world = world
    world.use_nodes = True
    bg = world.node_tree.nodes["Background"]
    bg.inputs[0].default_value = (0.05, 0.06, 0.08, 1)
    bg.inputs[1].default_value = 0.4

    # Key light
    bpy.ops.object.light_add(type="AREA", location=(4, -6, 5))
    key = bpy.context.active_object
    key.data.energy = 800
    key.data.size = 4

    bpy.ops.object.light_add(type="AREA", location=(-3, 4, 4))
    fill = bpy.context.active_object
    fill.data.energy = 250
    fill.data.size = 3

    scene.render.engine = spec.get("render_engine", "BLENDER_EEVEE_NEXT")
    # Fall back for Blender 4.2 naming
    engines = bpy.types.RenderSettings.bl_rna.properties["engine"].enum_items.keys()
    if scene.render.engine not in engines:
        scene.render.engine = "BLENDER_EEVEE"
    scene.render.resolution_x = int(spec.get("resolution", [1280, 720])[0])
    scene.render.resolution_y = int(spec.get("resolution", [1280, 720])[1])
    scene.render.filepath = str(out / "render_")
    scene.render.image_settings.file_format = "PNG"

    cam_data = bpy.data.cameras.new("PreviewCam")
    cam_obj = bpy.data.objects.new("PreviewCam", cam_data)
    scene.collection.objects.link(cam_obj)
    scene.camera = cam_obj
    cam_data.lens = 35

    for i, view in enumerate(renders):
        loc = view.get("location", [6, -8, 3])
        target = view.get("target", [0, 6, 1.2])
        cam_obj.location = Vector(loc)
        direction = Vector(target) - cam_obj.location
        cam_obj.rotation_euler = direction.to_track_quat("-Z", "Y").to_euler()
        path = out / view.get("filename", f"view_{i:02d}.png")
        scene.render.filepath = str(path)
        bpy.ops.render.render(write_still=True)
        metrics["renders"].append({
            "path": str(path),
            "bytes": path.stat().st_size if path.is_file() else 0,
            "location": loc,
            "target": target,
        })

metrics_path = out / "metrics.json"
metrics_path.write_text(json.dumps(metrics, indent=2, sort_keys=True), encoding="utf-8")
print("PROCEDURAL_EMIT_OK", metrics_path)
'''


@dataclass(slots=True)
class EmitResult:
    blend_path: Path
    glb_path: Path
    metrics_path: Path
    metrics: dict[str, Any]
    script_path: Path
    log_path: Path
    render_paths: list[Path] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "blend_path": str(self.blend_path),
            "glb_path": str(self.glb_path),
            "metrics_path": str(self.metrics_path),
            "script_path": str(self.script_path),
            "log_path": str(self.log_path),
            "render_paths": [str(p) for p in self.render_paths],
            "metrics": self.metrics,
        }


def _blender_executable() -> str:
    capability = discover_blender()
    if not capability.available or not capability.path:
        raise BackendUnavailable(
            "Blender executable was not found; set BVMCP_BLENDER_PATH or install Blender"
        )
    return capability.path


def build_emit_spec_for_archetype(
    archetype: Archetype,
    *,
    lod: str = LodLevel.NEAR.value,
) -> dict[str, Any]:
    parts = filter_parts_for_lod(archetype.build(), lod)
    return {
        "name": archetype.name,
        "lod": lod,
        "parts": [part.to_dict() for part in parts],
        "declared_dimensions": archetype.declared_dimensions().to_dict(),
    }


def build_emit_spec_for_plan(
    plan: InstancingPlan,
    *,
    library: ArchetypeLibrary | None = None,
    lod: str = LodLevel.NEAR.value,
    blend_name: str = "scene.blend",
    glb_name: str = "scene.glb",
    renders: list[dict[str, Any]] | None = None,
    render_engine: str = "BLENDER_EEVEE_NEXT",
) -> dict[str, Any]:
    library = library or default_library()
    prototypes: list[dict[str, Any]] = []
    for proto in plan.prototypes:
        arch = library.create(proto.archetype, proto.params)
        parts = filter_parts_for_lod(arch.build(), lod)
        prototypes.append(
            {
                "prototype_id": proto.prototype_id,
                "archetype": proto.archetype,
                "params": dict(proto.params),
                "lod": lod,
                "parts": [part.to_dict() for part in parts],
            }
        )
    return {
        "prototypes": prototypes,
        "placements": [item.to_dict() for item in plan.placements],
        "blend_name": blend_name,
        "glb_name": glb_name,
        "renders": list(renders or []),
        "render_engine": render_engine,
        "resolution": [1280, 720],
    }


def write_emit_script(
    emit_spec: dict[str, Any],
    output_dir: Path,
) -> tuple[Path, Path]:
    """Write emit_spec.json + emit_blender.py without running Blender."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    spec_path = output_dir / "emit_spec.json"
    script_path = output_dir / "emit_blender.py"
    payload = dict(emit_spec)
    payload["output_dir"] = str(output_dir.resolve())
    atomic_write_json(spec_path, payload)
    script = BLENDER_SCRIPT_TEMPLATE.replace("__SPEC_PATH__", str(spec_path.resolve()))
    atomic_write_text(script_path, textwrap.dedent(script).lstrip())
    return spec_path, script_path


def emit_to_blender(
    emit_spec: dict[str, Any],
    output_dir: Path,
    *,
    timeout_seconds: int = 600,
) -> EmitResult:
    """Run headless Blender against a generated emission script."""
    output_dir = Path(output_dir)
    _, script_path = write_emit_script(emit_spec, output_dir)
    log_path = output_dir / "emit.log"

    executable = _blender_executable()
    command = [
        executable,
        "--background",
        "--factory-startup",
        "--python-exit-code",
        "1",
        "--python",
        str(script_path),
    ]
    environment = os.environ.copy()
    environment["BVMCP_NETWORK_DISABLED"] = "1"
    proxy_vars = (
        "HTTP_PROXY",
        "HTTPS_PROXY",
        "ALL_PROXY",
        "http_proxy",
        "https_proxy",
        "all_proxy",
    )
    for name in proxy_vars:
        environment.pop(name, None)

    result = subprocess.run(
        command,
        cwd=str(output_dir),
        env=environment,
        capture_output=True,
        text=True,
        timeout=timeout_seconds,
        check=False,
    )
    log_path.write_text(
        (result.stdout or "") + "\n--- STDERR ---\n" + (result.stderr or ""),
        encoding="utf-8",
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"Blender emit failed with exit code {result.returncode}; see {log_path}"
        )

    metrics_path = output_dir / "metrics.json"
    if not metrics_path.is_file():
        raise RuntimeError(f"Blender emit completed without metrics.json; see {log_path}")
    metrics = json.loads(metrics_path.read_text(encoding="utf-8"))
    default_blend = output_dir / emit_spec.get("blend_name", "scene.blend")
    default_glb = output_dir / emit_spec.get("glb_name", "scene.glb")
    blend_path = Path(metrics.get("blend_path", default_blend))
    glb_path = Path(metrics.get("glb_path", default_glb))
    render_paths = [Path(item["path"]) for item in metrics.get("renders", [])]
    return EmitResult(
        blend_path=blend_path,
        glb_path=glb_path,
        metrics_path=metrics_path,
        metrics=metrics,
        script_path=script_path,
        log_path=log_path,
        render_paths=render_paths,
    )


def emit_with_fallback(
    emit_spec: dict[str, Any],
    output_dir: Path,
    *,
    plan: InstancingPlan | None = None,
    library: ArchetypeLibrary | None = None,
    archetype_name: str | None = None,
    archetype_params: dict[str, Any] | None = None,
    timeout_seconds: int = 600,
    force_offline: bool = False,
) -> EmitResult:
    """Prefer Blender; if blocked, emit real meshes via trimesh offline."""
    from blender_vision.procedural.mesh_offline import (
        blender_probe,
        emit_offline_archetype,
        emit_offline_scene,
    )

    output_dir = Path(output_dir)
    write_emit_script(emit_spec, output_dir)
    probe = blender_probe()
    if not force_offline and not probe.get("blocked"):
        try:
            return emit_to_blender(
                emit_spec, output_dir, timeout_seconds=timeout_seconds
            )
        except Exception as error:  # noqa: BLE001
            probe = {
                "blocked": True,
                "reason": f"Blender run failed after probe: {error}",
            }

    # Offline path — real geometry, no silent empty stubs.
    if plan is not None:
        offline = emit_offline_scene(plan, output_dir, library=library)
    elif archetype_name is not None:
        offline = emit_offline_archetype(
            archetype_name,
            output_dir,
            params=archetype_params,
            library=library,
        )
    else:
        raise BackendUnavailable(
            "Blender blocked and no offline emit target was provided: "
            f"{probe.get('reason', 'unknown')}"
        )

    metrics = dict(offline["metrics"])
    metrics["blender_probe"] = probe
    metrics["blender_status"] = "BLOCKED"
    metrics["blocked_reason"] = probe.get("reason", "Blender unavailable")
    metrics_path = Path(offline["metrics_path"])
    atomic_write_json(metrics_path, metrics)
    log_path = output_dir / "emit.log"
    log_path.write_text(
        "BLENDER_BLOCKED\n" + str(probe.get("reason", "")) + "\n",
        encoding="utf-8",
    )
    return EmitResult(
        blend_path=Path(metrics.get("blend_path", output_dir / "scene.blend.BLOCKED.txt")),
        glb_path=Path(offline["glb_path"]),
        metrics_path=metrics_path,
        metrics=metrics,
        script_path=output_dir / "emit_blender.py",
        log_path=log_path,
        render_paths=list(offline.get("render_paths", [])),
    )


def emit_archetype(
    name: str,
    output_dir: Path,
    *,
    params: dict[str, Any] | None = None,
    library: ArchetypeLibrary | None = None,
    lods: tuple[str, ...] = (LodLevel.NEAR.value, LodLevel.MID.value, LodLevel.FAR.value),
    timeout_seconds: int = 300,
) -> EmitResult:
    """Build a single archetype at multiple LODs into one .blend/.glb."""
    library = library or default_library()
    arch = library.create(name, params)
    builds = []
    for lod in lods:
        builds.append(build_emit_spec_for_archetype(arch, lod=lod))
    # Use near as the sole prototype for display; all LODs recorded as archetype_builds.
    near_parts = filter_parts_for_lod(arch.build(), LodLevel.NEAR.value)
    emit_spec = {
        "prototypes": [
            {
                "prototype_id": f"proto_{name}",
                "archetype": name,
                "params": dict(arch.params),
                "lod": LodLevel.NEAR.value,
                "parts": [part.to_dict() for part in near_parts],
            }
        ],
        "placements": [
            {
                "instance_id": f"{name}_instance",
                "prototype_id": f"proto_{name}",
                "location": [0.0, 0.0, 0.0],
                "rotation_euler": [0.0, 0.0, 0.0],
                "scale": [1.0, 1.0, 1.0],
                "state": {},
                "tags": [],
            }
        ],
        "archetype_builds": builds,
        "blend_name": f"{name}.blend",
        "glb_name": f"{name}.glb",
        "renders": [],
    }
    return emit_with_fallback(
        emit_spec,
        output_dir,
        library=library,
        archetype_name=name,
        archetype_params=params,
        timeout_seconds=timeout_seconds,
    )


def emit_scene_plan(
    plan: InstancingPlan,
    output_dir: Path,
    *,
    library: ArchetypeLibrary | None = None,
    renders: list[dict[str, Any]] | None = None,
    timeout_seconds: int = 900,
) -> EmitResult:
    emit_spec = build_emit_spec_for_plan(
        plan,
        library=library,
        renders=renders,
    )
    return emit_with_fallback(
        emit_spec,
        output_dir,
        plan=plan,
        library=library,
        timeout_seconds=timeout_seconds,
    )


def parts_triangle_estimate(parts: list[PartSpec]) -> int:
    """CPU-side triangle estimate without Blender (for LOD budgets)."""
    total = 0
    for part in parts:
        for item in part.walk():
            kind = item.geometry.kind.value
            if kind in {"box", "panel", "light_cell"}:
                total += 12
            elif kind == "hollow_box":
                total += 12 * 5
            elif kind == "cylinder":
                seg = max(8, item.geometry.segments)
                total += seg * 4
            elif kind == "vent_field":
                total += 12 * item.geometry.count_x * max(1, item.geometry.count_z)
            elif kind == "bundle":
                total += 8 * 4 * max(1, item.geometry.count_x)
            else:
                total += 12
    return total


def lod_triangle_report(archetype: Archetype) -> dict[str, Any]:
    variants = generate_lods(archetype.build())
    return {
        level: {
            "triangle_estimate": parts_triangle_estimate(variant.parts),
            "triangle_budget": variant.triangle_budget,
            "part_count": len(variant.part_names),
            "dimensions_m": variant.dimensions.to_dict(),
        }
        for level, variant in variants.items()
    }
