package main

import (
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/google/uuid"
)

// Token counts arrive in the upstream's own final usage message, and the
// upstream is the supplier's runtime. Left unbounded, that is the supplier
// writing its own invoice: stream "ok", report usage near the contract maximum,
// get paid for tokens nobody generated.
//
// Generated bytes are the independent measure the control plane already holds,
// because it proxies and hashes the stream itself.

func streamOf(lines ...string) string {
	return strings.Join(append(lines, `data: [DONE]`, ""), "\n\n") + "\n"
}

func trackStream(t *testing.T, stream string) (*streamEvidenceTracker, error) {
	t.Helper()
	tracker := newStreamEvidenceTracker(time.Now())
	mustf(t, proxySSE(httptest.NewRecorder(), strings.NewReader(stream), tracker), "proxy rejected the stream: %v")
	_, err := tracker.evidence(uuid.New(), 200, time.Second)
	return tracker, err
}

func TestUsageBeyondTheGeneratedStreamIsRefused(t *testing.T) {
	// The attack: two bytes of output, a bill for 4000 tokens.
	stream := streamOf(
		`data: {"id":"c","choices":[{"delta":{"content":"ok"}}]}`,
		`data: {"id":"c","choices":[],"usage":{"prompt_tokens":10,"completion_tokens":4000,"total_tokens":4010}}`,
	)
	_, err := trackStream(t, stream)
	if err == nil {
		t.Fatal("a bill far beyond the generated stream was accepted")
	}
	if !strings.Contains(err.Error(), "generated bytes") {
		t.Fatalf("refusal does not name the measurement: %v", err)
	}
}

func TestAnHonestResponseIsNeverRefused(t *testing.T) {
	// Roughly four bytes per token is ordinary for English, so an honest
	// response sits well inside the ceiling. This is the false-positive guard:
	// refusing real work would mean refusing to pay a supplier who did it.
	body := strings.Repeat("the quick brown fox ", 20) // 400 bytes
	stream := streamOf(
		`data: {"id":"c","choices":[{"delta":{"content":"`+body+`"}}]}`,
		`data: {"id":"c","choices":[],"usage":{"prompt_tokens":12,"completion_tokens":100,"total_tokens":112}}`,
	)
	if _, err := trackStream(t, stream); err != nil {
		t.Fatalf("an honest response was refused: %v", err)
	}
}

func TestTokensGeneratedOutsideVisibleContentStillCount(t *testing.T) {
	// Tool-call arguments and reasoning traces are generated tokens that never
	// appear as content. Counting only content would refuse these honest shapes.
	for name, stream := range map[string]string{
		"tool calls": streamOf(
			`data: {"id":"c","choices":[{"delta":{"tool_calls":[{"function":{"name":"lookup","arguments":"{\"query\":\"a somewhat lengthy argument payload here\"}"}}]}}]}`,
			`data: {"id":"c","choices":[],"usage":{"prompt_tokens":5,"completion_tokens":12,"total_tokens":17}}`,
		),
		"reasoning": streamOf(
			`data: {"id":"c","choices":[{"delta":{"reasoning_content":"thinking through the problem step by step here"}}]}`,
			`data: {"id":"c","choices":[],"usage":{"prompt_tokens":5,"completion_tokens":11,"total_tokens":16}}`,
		),
		"legacy completion text": streamOf(
			`data: {"id":"c","choices":[{"text":"a legacy completion response body of some length"}]}`,
			`data: {"id":"c","choices":[],"usage":{"prompt_tokens":5,"completion_tokens":11,"total_tokens":16}}`,
		),
	} {
		if _, err := trackStream(t, stream); err != nil {
			t.Fatalf("%s: honest generation refused: %v", name, err)
		}
	}
}

func TestUsageWithNoGeneratedOutputAtAllIsRefused(t *testing.T) {
	// A stream that generated nothing cannot have produced completion tokens.
	stream := streamOf(
		`data: {"id":"c","choices":[{"delta":{"role":"assistant"}}]}`,
		`data: {"id":"c","choices":[],"usage":{"prompt_tokens":8,"completion_tokens":50,"total_tokens":58}}`,
	)
	if _, err := trackStream(t, stream); err == nil {
		t.Fatal("completion tokens were billed against an empty stream")
	}
}

func TestAZeroCompletionResponseIsAccepted(t *testing.T) {
	// An immediately-stopped generation bills nothing and must not be refused.
	stream := streamOf(
		`data: {"id":"c","choices":[{"delta":{"role":"assistant"}}]}`,
		`data: {"id":"c","choices":[],"usage":{"prompt_tokens":8,"completion_tokens":0,"total_tokens":8}}`,
	)
	if _, err := trackStream(t, stream); err != nil {
		t.Fatalf("a zero-completion response was refused: %v", err)
	}
}

func TestGeneratedBytesAccumulateAcrossDeltas(t *testing.T) {
	// Real streams arrive as many small deltas; the ceiling is the sum, not the
	// largest single delta.
	var lines []string
	for i := 0; i < 40; i++ {
		lines = append(lines, `data: {"id":"c","choices":[{"delta":{"content":"token "}}]}`)
	}
	lines = append(lines,
		`data: {"id":"c","choices":[],"usage":{"prompt_tokens":3,"completion_tokens":40,"total_tokens":43}}`)

	tracker, err := trackStream(t, streamOf(lines...))
	mustf(t, err, "accumulated deltas were refused: %v")
	// 40 deltas x len(`"token "`) - the measure is the raw JSON value, so it
	// carries the two surrounding quotes. That over-counts by 2 bytes per delta,
	// which only loosens a ceiling that must never refuse honest work.
	if tracker.generatedBytes != 320 {
		t.Fatalf("generated bytes = %d, want 320", tracker.generatedBytes)
	}
}

func TestTheBoundIsTheSameRuleOnBothPaths(t *testing.T) {
	// The non-streaming JSON path builds its own evidence and would otherwise
	// have kept the hole the streaming path closed.
	if err := boundCompletionTokens(4000, 2); err == nil {
		t.Fatal("a bill beyond the observed output was accepted")
	}
	mustf(t, boundCompletionTokens(100, 400), "an honest bill was refused: %v")
	mustf(t, boundCompletionTokens(0, 0), "a zero-completion response was refused: %v")
	// Exactly at the ceiling is honest: a one-byte-per-token response is real.
	mustf(t, boundCompletionTokens(50, 50), "a dense but real response was refused: %v")
}
