#!/usr/bin/env bash
# Produce a MERC_* .env from the droplet's existing CX_* one.
#
# Writes a CANDIDATE file (.env.merc) and changes nothing that is running. The
# live site has been up for weeks; this is the part that can be prepared and
# read before anything is cut over.
#
#   bash droplet-env-cutover.sh          # write .env.merc, report the gap
#   bash droplet-env-cutover.sh --apply  # back up .env and replace it
#
# The one that matters: CX_TOKEN_KEY is copied BYTE-IDENTICALLY into
# MERC_TOKEN_KEY. control/crypto.go derives the AES key as sha256(value), so a
# freshly generated value makes every sealed OAuth token and webhook secret
# already in Postgres permanently undecryptable. It is never regenerated here.

set -euo pipefail
umask 077

ENV_FILE="${ENV_FILE:-/opt/computexchange/.env}"
OUT="${ENV_FILE}.merc"
APPLY=0
[ "${1:-}" = "--apply" ] && APPLY=1

ok()   { printf '  \033[32mOK\033[0m    %s\n' "$*"; }
bad()  { printf '  \033[31mNEED\033[0m  %s\n' "$*"; }
note() { printf '  \033[33m..\033[0m    %s\n' "$*"; }
die()  { printf '\nSTOPPED: %s\n' "$*" >&2; exit 1; }

[ -f "$ENV_FILE" ] || die "$ENV_FILE not found"
# shellcheck disable=SC1090
set -a; . "$ENV_FILE"; set +a

printf 'merc env cutover (candidate only)\n\n'

# Values that must be CARRIED OVER, never regenerated. Losing any of these
# breaks something already stored in the database.
declare -a CARRY=(
  "CX_TOKEN_KEY:MERC_TOKEN_KEY:seals OAuth tokens and webhook secrets in Postgres"
  "CX_CONNECT_WEBHOOK_SECRET:MERC_CONNECT_WEBHOOK_SECRET:Stripe Connect signature validation"
  "CX_CONNECT_RETURN_URL:MERC_CONNECT_RETURN_URL:Connect onboarding return"
  "CX_CONNECT_REFRESH_URL:MERC_CONNECT_REFRESH_URL:Connect onboarding refresh"
  "CX_STATE_SECRET:MERC_STATE_SECRET:OAuth state signing"
  "CX_WORKER_TOKEN:MERC_WORKER_TOKEN:existing worker authentication"
  "CX_CONTROL_URL:MERC_PUBLIC_CONTROL_ORIGIN:public control origin"
  "CX_ADMIN_ORIGIN:MERC_ADMIN_ORIGIN:admin WebAuthn origin"
  "CX_ADMIN_RP_ID:MERC_ADMIN_RP_ID:admin WebAuthn relying party"
)

{
  printf '# merc environment. Generated by droplet-env-cutover.sh from the CX_* file.\n'
  printf '# Carried-over values are byte-identical to the originals.\n\n'

  # Everything that was not a CX_ name passes through untouched.
  grep -vE '^\s*(#|$)' "$ENV_FILE" | grep -vE '^CX_' || true
  printf '\n# --- carried over from CX_* ---\n'
} > "$OUT"

printf 'carried over (byte-identical)\n'
for spec in "${CARRY[@]}"; do
  old="${spec%%:*}"; rest="${spec#*:}"; new="${rest%%:*}"; why="${rest#*:}"
  val="${!old:-}"
  if [ -n "$val" ]; then
    printf '%s=%q\n' "$new" "$val" >> "$OUT"
    ok "$old -> $new  ($why)"
  else
    note "$old not set; skipping $new"
  fi
done

# Secrets that are genuinely NEW: nothing in the database was encrypted with
# them, so generating one is safe. Generating MERC_TOKEN_KEY would not be, which
# is why it is in CARRY above and not here.
printf '\ngenerated (new secrets, nothing depends on a previous value)\n'
for name in MERC_VERIFICATION_SAMPLE_SECRET; do
  if [ -z "${!name:-}" ]; then
    printf '%s=%q\n' "$name" "$(openssl rand -hex 32)" >> "$OUT"
    ok "$name generated (32 bytes)"
  else
    printf '%s=%q\n' "$name" "${!name}" >> "$OUT"
    ok "$name carried over"
  fi
done

# Deployment identity the new build needs and the old one never had.
printf '\ndeployment settings\n'
{
  printf 'MERC_ENV=production\n'
  printf 'SITE_HOST=%s\n' "${SITE_HOST:-mercmerc.net}"
} >> "$OUT"
ok "MERC_ENV=production (gates the hardening refusal)"
ok "SITE_HOST=${SITE_HOST:-mercmerc.net}"

# Business values. Deliberately NOT invented here: these set what merc charges
# and what it keeps, and a number guessed by a script is a number nobody chose.
printf '\nstill needed — these are business decisions, not defaults\n'
MISSING=0
for name in MERC_SETTLEMENT_CURRENCY MERC_PRICE_REFERENCE_TO_SETTLEMENT_RATE MERC_PRICE_FX_REVISION \
            MERC_ECON_SCHEDULE_VERSION MERC_PROCESSOR_PERCENT_BPS MERC_PROCESSOR_FIXED_USD \
            MERC_CONTROL_PLANE_PER_TASK_USD MERC_TARGET_MARGIN_BPS \
            MERC_ALERT_RECEIVER_URL_FILE GF_SECURITY_ADMIN_PASSWORD; do
  if [ -z "${!name:-}" ]; then bad "$name"; MISSING=$((MISSING+1))
  else printf '%s=%q\n' "$name" "${!name}" >> "$OUT"; ok "$name already set"; fi
done

chmod 600 "$OUT"
printf '\nwrote %s (chmod 600)\n' "$OUT"

if [ "$MISSING" -gt 0 ]; then
  printf '\n%d value(s) still needed. The control plane refuses to boot without\n' "$MISSING"
  printf 'them, so --apply is refused until they are added to %s.\n' "$OUT"
  [ "$APPLY" -eq 1 ] && die "not applying an env that cannot boot"
  exit 0
fi

if [ "$APPLY" -eq 1 ]; then
  backup="${ENV_FILE}.bak.$(date +%Y%m%d%H%M%S)"
  cp -p "$ENV_FILE" "$backup"
  chmod 600 "$backup"
  mv "$OUT" "$ENV_FILE"
  printf '\napplied. previous file kept at %s\n' "$backup"
  printf 'nothing was restarted; the running containers still use the old values\n'
  printf 'until you recreate them.\n'
else
  printf '\nreview it, then re-run with --apply. Nothing has changed yet.\n'
fi
