# Auto-generated by blender_vision.procedural.emit — do not hand-edit.
import json
import math
import sys
from pathlib import Path

import bpy
from mathutils import Euler, Matrix, Vector

SPEC_PATH = Path(r"""/Users/scammermike/.claude-grok/worktrees/ocular-beat-lighting-20260727-160959/tools/blender-vision-mcp/artifacts/ocular/beats/_probe_light/emit_spec.json""")
spec = json.loads(SPEC_PATH.read_text(encoding="utf-8"))
out = Path(spec["output_dir"])
out.mkdir(parents=True, exist_ok=True)

# --factory-startup already gave us a clean scene; do not re-read home file
# (read_factory_settings can re-trigger Metal GPU init crashes on some hosts).
scene = bpy.context.scene
scene.unit_settings.system = "METRIC"
scene.unit_settings.scale_length = 1.0
for obj in list(bpy.data.objects):
    bpy.data.objects.remove(obj, do_unlink=True)


def ensure_collection(name, parent=None):
    col = bpy.data.collections.get(name)
    if col is None:
        col = bpy.data.collections.new(name)
        if parent is None:
            scene.collection.children.link(col)
        else:
            parent.children.link(col)
    return col


def ensure_material(name):
    mat = bpy.data.materials.get(name)
    if mat is None:
        mat = bpy.data.materials.new(name=name)
        mat.use_nodes = True
        nodes = mat.node_tree.nodes
        bsdf = nodes.get("Principled BSDF")
        if bsdf:
            # Neutral placeholder; inverse-materials subsystem owns real shading.
            # Mid-dark set palette: resolvable under ceiling practicals, but
            # dark enough that declared text-safe zones keep ≥3:1 contrast.
            colour = {
                "steel": (0.22, 0.24, 0.26, 1),
                "chassis": (0.055, 0.055, 0.06, 1),
                "bezel": (0.04, 0.04, 0.045, 1),
                "vent": (0.05, 0.05, 0.06, 1),
                "metal": (0.32, 0.32, 0.34, 1),
                "drive": (0.14, 0.14, 0.16, 1),
                "gpu": (0.10, 0.16, 0.12, 1),
                "heatsink": (0.28, 0.28, 0.30, 1),
                "connector": (0.04, 0.04, 0.04, 1),
                "led": (0.1, 0.8, 0.2, 1),
                "port": (0.28, 0.38, 0.14, 1),
                "fan": (0.06, 0.06, 0.06, 1),
                "blanking": (0.12, 0.12, 0.13, 1),
                "pdu": (0.08, 0.10, 0.22, 1),
                "outlet": (0.4, 0.4, 0.42, 1),
                "breaker": (0.4, 0.12, 0.08, 1),
                "tray": (0.22, 0.20, 0.14, 1),
                "cable": (0.04, 0.04, 0.04, 1),
                "cooling": (0.35, 0.38, 0.42, 1),
                "louvre": (0.28, 0.30, 0.32, 1),
                "floor": (0.14, 0.14, 0.15, 1),
                "ceiling": (0.18, 0.18, 0.20, 1),
                "grid": (0.28, 0.28, 0.30, 1),
                "wall": (0.12, 0.13, 0.15, 1),
                "concrete": (0.20, 0.20, 0.21, 1),
                "threshold": (0.16, 0.15, 0.14, 1),
                "door": (0.10, 0.11, 0.13, 1),
                "aisle_cold": (0.08, 0.10, 0.14, 1),
                "aisle_hot": (0.14, 0.08, 0.07, 1),
                "guide": (0.35, 0.32, 0.12, 1),
                "volume": (0.18, 0.18, 0.20, 1),
                "junction": (0.12, 0.12, 0.13, 1),
                "structure": (0.16, 0.16, 0.17, 1),
                "containment": (0.14, 0.16, 0.18, 1),
                "glass": (0.35, 0.42, 0.45, 1),
                "seal": (0.06, 0.06, 0.06, 1),
                "panel": (0.14, 0.14, 0.15, 1),
                "baseboard": (0.18, 0.18, 0.19, 1),
                "cornice": (0.32, 0.32, 0.34, 1),
                "status_ok": (0.1, 0.9, 0.2, 1),
                "status_warn": (0.95, 0.75, 0.1, 1),
                "status_fault": (0.95, 0.15, 0.1, 1),
                "status_off": (0.10, 0.10, 0.10, 1),
                "status_maintenance": (0.2, 0.4, 0.9, 1),
                "status_cell": (0.2, 0.8, 0.3, 1),
                "neutral": (0.28, 0.28, 0.28, 1),
            }.get(name, (0.28, 0.28, 0.28, 1))
            bsdf.inputs["Base Color"].default_value = colour
            # Keep materials matte so ceiling fixtures model hierarchy instead of
            # mirror-blooming into the text-safe zone.
            if "Roughness" in bsdf.inputs:
                bsdf.inputs["Roughness"].default_value = 0.55 if name in {
                    "metal", "heatsink", "tray", "cooling", "louvre",
                } else 0.72
            if "Specular IOR Level" in bsdf.inputs:
                bsdf.inputs["Specular IOR Level"].default_value = 0.25
            elif "Specular" in bsdf.inputs:
                bsdf.inputs["Specular"].default_value = 0.25
            if name.startswith("status_") or name == "led":
                bsdf.inputs["Emission Color"].default_value = colour
                if "Emission Strength" in bsdf.inputs:
                    # Practical rack/status LEDs — local accents, not the aisle key.
                    bsdf.inputs["Emission Strength"].default_value = 5.0
    return mat


def link_object(obj, collection):
    for col in list(obj.users_collection):
        col.objects.unlink(obj)
    collection.objects.link(obj)


def apply_transform(obj, transform):
    loc = transform.get("location", [0, 0, 0])
    rot = transform.get("rotation_euler", [0, 0, 0])
    scale = transform.get("scale", [1, 1, 1])
    obj.location = Vector(loc)
    obj.rotation_euler = Euler(rot, "XYZ")
    obj.scale = Vector(scale)


def make_box(name, size, collection, material):
    bpy.ops.mesh.primitive_cube_add(size=1.0, location=(0, 0, 0))
    obj = bpy.context.active_object
    obj.name = name
    obj.data.name = name + "_mesh"
    obj.scale = Vector(size)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    if material:
        obj.data.materials.append(ensure_material(material))
    link_object(obj, collection)
    return obj


def make_cylinder(name, size, segments, collection, material):
    # size = (diameter_x, diameter_y, height_z) in local space before object transform
    radius = 0.5 * max(size[0], size[1])
    depth = size[2]
    bpy.ops.mesh.primitive_cylinder_add(
        vertices=max(8, int(segments)),
        radius=radius,
        depth=depth,
        location=(0, 0, 0),
    )
    obj = bpy.context.active_object
    obj.name = name
    obj.data.name = name + "_mesh"
    if material:
        obj.data.materials.append(ensure_material(material))
    link_object(obj, collection)
    return obj


def make_hollow_box(name, size, wall, open_face, collection, material):
    # Outer box minus inner (approx via solidify on open box shell using 5 faces as boxes)
    sx, sy, sz = size
    t = max(wall, 0.001)
    parts = []
    # +X -X walls
    for sign, label in ((1, "px"), (-1, "nx")):
        if open_face in (f"{'+' if sign>0 else '-'}X",):
            continue
        o = make_box(f"{name}_{label}", (t, sy, sz), collection, material)
        o.data.transform(Matrix.Translation((sign * (sx * 0.5 - t * 0.5), 0.0, 0.0)))
        parts.append(o)
    for sign, label in ((1, "py"), (-1, "ny")):
        if open_face in (f"{'+' if sign>0 else '-'}Y",):
            continue
        o = make_box(f"{name}_{label}", (sx, t, sz), collection, material)
        o.data.transform(Matrix.Translation((0.0, sign * (sy * 0.5 - t * 0.5), 0.0)))
        parts.append(o)
    for sign, label in ((1, "pz"), (-1, "nz")):
        if open_face in (f"{'+' if sign>0 else '-'}Z",):
            continue
        o = make_box(f"{name}_{label}", (sx, sy, t), collection, material)
        o.data.transform(Matrix.Translation((0.0, 0.0, sign * (sz * 0.5 - t * 0.5))))
        parts.append(o)
    if not parts:
        return make_box(name, size, collection, material)
    # Join walls into one object with semantic name
    bpy.ops.object.select_all(action="DESELECT")
    for o in parts:
        o.select_set(True)
    bpy.context.view_layer.objects.active = parts[0]
    bpy.ops.object.join()
    obj = bpy.context.active_object
    obj.name = name
    obj.data.name = name + "_mesh"
    return obj


def make_vent_field(name, geom, collection, material):
    sx, sy, sz = geom["size"]
    cx = max(1, int(geom.get("count_x", 1)))
    cz = max(1, int(geom.get("count_z", 1)))
    pitch = geom.get("pitch", [sx / cx, 0.0, sz / cz])
    cell = geom.get("cell_size", [pitch[0] * 0.5, sy, pitch[2] * 0.5])
    parts = []
    for iz in range(cz):
        for ix in range(cx):
            x = (ix - (cx - 1) * 0.5) * pitch[0]
            z = (iz - (cz - 1) * 0.5) * pitch[2]
            o = make_box(f"{name}_{ix}_{iz}", cell, collection, material)
            # Offset the mesh data, not the object. join() adopts the first
            # object's origin, so moving objects here would put the joined
            # origin on a corner cell and the part transform would be applied
            # relative to that instead of to the field centre.
            o.data.transform(Matrix.Translation((x, 0.0, z)))
            parts.append(o)
    if not parts:
        return make_box(name, geom["size"], collection, material)
    bpy.ops.object.select_all(action="DESELECT")
    for o in parts:
        o.select_set(True)
    bpy.context.view_layer.objects.active = parts[0]
    bpy.ops.object.join()
    obj = bpy.context.active_object
    obj.name = name
    obj.data.name = name + "_mesh"
    return obj


def make_light_cell(name, geom, collection, material):
    return make_box(name, geom["size"], collection, material)


def make_bundle(name, geom, collection, material):
    # Multi-strand cylinder approximation along local Z
    strands = max(1, int(geom.get("count_x", geom.get("extras", {}).get("strand_count", 6))))
    dia = max(geom["size"][0], geom["size"][1])
    length = geom["size"][2]
    core_r = dia * 0.5
    strand_r = core_r / max(2.5, math.sqrt(strands))
    parts = []
    for i in range(strands):
        ang = 2 * math.pi * i / strands
        r = core_r * 0.45
        bpy.ops.mesh.primitive_cylinder_add(
            vertices=8,
            radius=strand_r,
            depth=length,
            location=(0.0, 0.0, 0.0),
        )
        o = bpy.context.active_object
        o.name = f"{name}_s{i}"
        # Mesh-data offset, not object location: join() adopts the first
        # strand's origin, which would shift the whole bundle.
        o.data.transform(Matrix.Translation((math.cos(ang) * r, math.sin(ang) * r, 0.0)))
        if material:
            o.data.materials.append(ensure_material(material))
        link_object(o, collection)
        parts.append(o)
    bpy.ops.object.select_all(action="DESELECT")
    for o in parts:
        o.select_set(True)
    bpy.context.view_layer.objects.active = parts[0]
    bpy.ops.object.join()
    obj = bpy.context.active_object
    obj.name = name
    obj.data.name = name + "_mesh"
    return obj


def build_geometry(name, geom, collection, material):
    kind = geom["kind"]
    if kind == "box" or kind == "panel":
        return make_box(name, geom["size"], collection, material)
    if kind == "cylinder":
        return make_cylinder(name, geom["size"], geom.get("segments", 12), collection, material)
    if kind == "hollow_box":
        return make_hollow_box(
            name, geom["size"], geom.get("wall_thickness", 0.002),
            geom.get("open_face", ""), collection, material,
        )
    if kind == "vent_field":
        return make_vent_field(name, geom, collection, material)
    if kind == "light_cell":
        return make_light_cell(name, geom, collection, material)
    if kind == "bundle" or kind == "tube":
        return make_bundle(name, geom, collection, material)
    return make_box(name, geom["size"], collection, material)


def build_part_tree(part, collection, parent_empty=None):
    geom = part["geometry"]
    obj = build_geometry(part["name"], geom, collection, part.get("material_slot", "neutral"))
    apply_transform(obj, part.get("transform", {}))
    if parent_empty is not None:
        obj.parent = parent_empty
    # State as custom properties (non-geometric)
    for key in part.get("state_keys", []):
        obj[key] = part.get("material_slot", "")
    children_root = obj
    for child in part.get("children", []):
        build_part_tree(child, collection, parent_empty=children_root)
    return obj


def triangle_count(objects):
    total = 0
    for obj in objects:
        if obj.type != "MESH" or obj.data is None:
            continue
        mesh = obj.data
        mesh.calc_loop_triangles()
        total += len(mesh.loop_triangles)
    return total


def world_bbox(objects):
    # Measure evaluated vertices, not obj.bound_box. bound_box is a cached,
    # pre-modifier value that is stale until the depsgraph catches up, which
    # reported this rack 10 mm taller than the geometry actually was.
    bpy.context.view_layer.update()
    depsgraph = bpy.context.evaluated_depsgraph_get()
    mins = Vector((1e9, 1e9, 1e9))
    maxs = Vector((-1e9, -1e9, -1e9))
    any_mesh = False
    for obj in objects:
        if obj.type != "MESH":
            continue
        evaluated = obj.evaluated_get(depsgraph)
        mesh = evaluated.to_mesh()
        try:
            if not mesh.vertices:
                continue
            any_mesh = True
            matrix = evaluated.matrix_world
            for vertex in mesh.vertices:
                w = matrix @ vertex.co
                mins.x = min(mins.x, w.x); mins.y = min(mins.y, w.y); mins.z = min(mins.z, w.z)
                maxs.x = max(maxs.x, w.x); maxs.y = max(maxs.y, w.y); maxs.z = max(maxs.z, w.z)
        finally:
            evaluated.to_mesh_clear()
    if not any_mesh:
        return [0, 0, 0], [0, 0, 0]
    return list(mins), list(maxs)


metrics = {"prototypes": {}, "instances": 0, "unique_meshes": 0, "renders": []}

# ---- Prototypes (one collection each, mesh data created once) ----
root_col = ensure_collection("ProceduralRoot")
proto_root = ensure_collection("Prototypes", root_col)
instance_root = ensure_collection("Instances", root_col)

prototype_collections = {}
for proto in spec.get("prototypes", []):
    pid = proto["prototype_id"]
    pcol = ensure_collection(pid, proto_root)
    pcol.hide_render = True
    pcol.hide_viewport = True
    for part in proto.get("parts", []):
        build_part_tree(part, pcol)
    objs = [o for o in pcol.objects]
    mins, maxs = world_bbox(objs)
    metrics["prototypes"][pid] = {
        "archetype": proto.get("archetype"),
        "lod": proto.get("lod", "near"),
        "triangle_count": triangle_count(objs),
        "bbox_min": mins,
        "bbox_max": maxs,
        "bbox_size": [maxs[i] - mins[i] for i in range(3)],
        "object_count": len(objs),
        "part_names": [o.name for o in objs],
    }
    prototype_collections[pid] = pcol

metrics["unique_meshes"] = len(prototype_collections)

# ---- Instances as collection instances (linked, not copies) ----
for placement in spec.get("placements", []):
    pid = placement["prototype_id"]
    pcol = prototype_collections.get(pid)
    if pcol is None:
        continue
    inst = bpy.data.objects.new(placement["instance_id"], None)
    inst.instance_type = "COLLECTION"
    inst.instance_collection = pcol
    apply_transform(inst, {
        "location": placement.get("location", [0, 0, 0]),
        "rotation_euler": placement.get("rotation_euler", [0, 0, 0]),
        "scale": placement.get("scale", [1, 1, 1]),
    })
    for k, v in placement.get("state", {}).items():
        inst[k] = v
    link_object(inst, instance_root)
    metrics["instances"] += 1

# Unhide instance root; keep prototypes hidden (instances still draw them)
for pcol in prototype_collections.values():
    pcol.hide_viewport = False  # required for collection instances to draw
    pcol.hide_render = False

# ---- Optional standalone archetype metrics (no placements) ----
for entry in spec.get("archetype_builds", []):
    name = entry["name"]
    lod = entry.get("lod", "near")
    acol = ensure_collection(f"arch_{name}_{lod}", root_col)
    for part in entry.get("parts", []):
        build_part_tree(part, acol)
    objs = [o for o in acol.objects]
    mins, maxs = world_bbox(objs)
    metrics.setdefault("archetypes", {})[f"{name}:{lod}"] = {
        "triangle_count": triangle_count(objs),
        "bbox_min": mins,
        "bbox_max": maxs,
        "bbox_size": [maxs[i] - mins[i] for i in range(3)],
        "object_count": len(objs),
        "part_names": sorted({o.name for o in objs}),
    }

# ---- Save .blend ----
blend_path = out / spec.get("blend_name", "scene.blend")
bpy.ops.wm.save_as_mainfile(filepath=str(blend_path))
metrics["blend_path"] = str(blend_path)
metrics["blend_bytes"] = blend_path.stat().st_size

# ---- Export GLB ----
glb_path = out / spec.get("glb_name", "scene.glb")
# Select all mesh-bearing content for export
bpy.ops.object.select_all(action="SELECT")
bpy.ops.export_scene.gltf(
    filepath=str(glb_path),
    export_format="GLB",
    use_selection=False,
    export_apply=False,
)
metrics["glb_path"] = str(glb_path)
metrics["glb_bytes"] = glb_path.stat().st_size if glb_path.is_file() else 0

# ---- Renders ----
renders = spec.get("renders") or []
if renders:
    # Data-centre practical lighting: light the *set*, not one spot.
    # Flagship bounds: main aisle along Y (≈ -1..12, x=0), second aisle along
    # +X (≈ 0..8.5, y≈13.2), ceiling at ~2.7–3.0 m. Two fixed lamps cannot
    # cover a 19 m walk; inverse-square collapses beat brightness as the
    # camera leaves the key. Ceiling runs + terminal rim keep every beat
    # camera inside a lit volume with a real key/fill/rim hierarchy.
    light_col = ensure_collection("set_lighting", scene.collection)

    world = bpy.data.worlds.new("World")
    scene.world = world
    world.use_nodes = True
    bg = world.node_tree.nodes["Background"]
    # Cool dim ambient only — hierarchy comes from local lamps, not the world.
    bg.inputs[0].default_value = (0.04, 0.045, 0.055, 1)
    bg.inputs[1].default_value = 0.22

    def add_area(name, location, energy, size, *, size_y=None, color=(1.0, 0.97, 0.92),
                 rot_euler=(0.0, 0.0, 0.0), shape="RECTANGLE"):
        bpy.ops.object.light_add(type="AREA", location=location)
        lamp = bpy.context.active_object
        lamp.name = name
        lamp.data.name = name + "_data"
        lamp.data.energy = float(energy)
        lamp.data.color = color
        if hasattr(lamp.data, "shape") and shape:
            try:
                lamp.data.shape = shape
            except Exception:
                pass
        if size_y is not None and hasattr(lamp.data, "size_y"):
            lamp.data.size = float(size)
            lamp.data.size_y = float(size_y)
        else:
            lamp.data.size = float(size)
        lamp.rotation_euler = Euler(rot_euler, "XYZ")
        link_object(lamp, light_col)
        return lamp

    # Point area lights straight down (local -Z).
    down = (0.0, 0.0, 0.0)
    # Main-aisle ceiling run: paired key/fill strips every 2 m.
    # Key slightly offset +X (warmer), fill −X (cooler, weaker).
    # Overhead only — no side-fire lamps (those blast rack faces at 0.5 m
    # and blow the text-safe zone to white).
    main_ys = [float(y) for y in range(-1, 13, 2)]
    for idx, y in enumerate(main_ys):
        add_area(
            f"ceil_main_key_{idx:02d}",
            (0.18, y, 2.95),
            energy=62.0,
            size=1.8,
            size_y=0.35,
            color=(1.0, 0.97, 0.92),
            rot_euler=down,
        )
        add_area(
            f"ceil_main_fill_{idx:02d}",
            (-0.18, y, 2.95),
            energy=30.0,
            size=1.8,
            size_y=0.35,
            color=(0.88, 0.93, 1.0),
            rot_euler=down,
        )

    # Second-aisle ceiling run along +X. Key biased north (+Y); south fill weaker.
    second_xs = [1.2, 3.0, 4.8, 6.6, 8.0]
    for idx, x in enumerate(second_xs):
        add_area(
            f"ceil_second_key_{idx:02d}",
            (x, 13.20 + 0.20, 2.95),
            energy=58.0,
            size=1.6,
            size_y=0.35,
            color=(1.0, 0.96, 0.90),
            rot_euler=down,
        )
        add_area(
            f"ceil_second_fill_{idx:02d}",
            (x, 13.20 - 0.20, 2.95),
            energy=10.0,
            size=1.6,
            size_y=0.35,
            color=(0.88, 0.93, 1.0),
            rot_euler=down,
        )

    # South-side light baffles: deep soffit that shadows the VERIFY right_upper
    # band on the south rack faces while the aisle floor stays lit.
    baffle_mat = ensure_material("bezel")
    for idx, x in enumerate([2.5, 4.0, 5.5, 7.0]):
        bpy.ops.mesh.primitive_cube_add(size=1.0, location=(x, 12.70, 2.35))
        baffle = bpy.context.active_object
        baffle.name = f"text_baffle_s_{idx:02d}"
        baffle.scale = Vector((1.6, 0.45, 0.35))
        bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
        if baffle_mat and baffle.data.materials is not None:
            baffle.data.materials.clear()
            baffle.data.materials.append(baffle_mat)
        link_object(baffle, light_col)

    # Entry key: stronger practical over the threshold approach.
    add_area(
        "entry_key",
        (0.0, -3.2, 3.0),
        energy=400.0,
        size=2.8,
        size_y=1.4,
        color=(1.0, 0.97, 0.92),
        rot_euler=down,
    )
    # Soft fill behind the threshold so the approach is not a black void.
    add_area(
        "entry_fill",
        (0.0, -5.5, 2.6),
        energy=180.0,
        size=3.2,
        size_y=2.2,
        color=(0.9, 0.94, 1.0),
        rot_euler=down,
    )
    # Bridge the threshold → first ceiling fixture so beat 01 is not a dark gap.
    add_area(
        "entry_bridge",
        (0.0, -1.8, 2.85),
        energy=120.0,
        size=2.0,
        size_y=1.0,
        color=(1.0, 0.97, 0.92),
        rot_euler=down,
    )
    add_area(
        "entry_forward",
        (0.0, 0.6, 2.85),
        energy=100.0,
        size=1.8,
        size_y=1.0,
        color=(1.0, 0.96, 0.9),
        rot_euler=down,
    )
    # Junction soft bounce so the turn is not a black corner.
    add_area(
        "junction_soft",
        (0.8, 13.0, 2.9),
        energy=45.0,
        size=2.2,
        size_y=2.2,
        color=(0.95, 0.97, 1.0),
        rot_euler=down,
    )
    # Terminal rim: soft back-light for ACCESS / RECEIPT depth (keep wall dark
    # enough for terminal_wall text contrast ≥ 3.5:1).
    add_area(
        "terminal_rim",
        (7.6, 13.20, 2.5),
        energy=28.0,
        size=1.4,
        size_y=0.8,
        color=(0.85, 0.9, 1.0),
        rot_euler=(0.0, math.radians(55.0), math.radians(180.0)),
    )

    # Engine: Cycles on CPU only. EEVEE_NEXT aborts headless on this host (exit 134).
    requested = str(spec.get("render_engine") or "CYCLES")
    if requested.upper() in {"BLENDER_EEVEE_NEXT", "BLENDER_EEVEE", "EEVEE", "EEVEE_NEXT"}:
        requested = "CYCLES"
    scene.render.engine = requested
    engines = bpy.types.RenderSettings.bl_rna.properties["engine"].enum_items.keys()
    if scene.render.engine not in engines:
        scene.render.engine = "CYCLES"

    samples = int(spec.get("samples", 32))
    if scene.render.engine == "CYCLES":
        scene.cycles.device = "CPU"
        scene.cycles.samples = samples
        scene.cycles.use_denoising = True
        # Prefer OIDN when present; ignore if the build lacks it.
        try:
            scene.cycles.denoiser = "OPENIMAGEDENOISE"
        except Exception:
            pass
        try:
            prefs = bpy.context.preferences.addons["cycles"].preferences
            prefs.compute_device_type = "NONE"
            prefs.get_devices()
            for dev in prefs.devices:
                dev.use = (dev.type == "CPU")
        except Exception:
            pass

    metrics["render_engine"] = scene.render.engine
    metrics["render_samples"] = samples
    metrics["render_device"] = "CPU" if scene.render.engine == "CYCLES" else "n/a"
    metrics["lighting"] = {
        "design": "datacentre_ceiling_runs_key_fill_rim",
        "main_aisle_fixtures": len(main_ys) * 2,
        "second_aisle_fixtures": len(second_xs) * 2,
        "practicals": [
            "entry_key",
            "entry_fill",
            "entry_forward",
            "entry_bridge",
            "junction_soft",
            "terminal_rim",
        ],
        "world_strength": 0.22,
        "notes": "Overhead ceiling runs only; no side-fire lamps against rack faces.",
    }

    scene.render.resolution_x = int(spec.get("resolution", [1280, 720])[0])
    scene.render.resolution_y = int(spec.get("resolution", [1280, 720])[1])
    scene.render.filepath = str(out / "render_")
    scene.render.image_settings.file_format = "PNG"
    # Do not raise film exposure / gamma to fake resolvability.
    if hasattr(scene.view_settings, "exposure"):
        scene.view_settings.exposure = float(spec.get("exposure", 0.0))
    if hasattr(scene.view_settings, "gamma"):
        scene.view_settings.gamma = float(spec.get("gamma", 1.0))

    cam_data = bpy.data.cameras.new("PreviewCam")
    cam_obj = bpy.data.objects.new("PreviewCam", cam_data)
    scene.collection.objects.link(cam_obj)
    scene.camera = cam_obj
    cam_data.lens = 35

    # Persist the lit scene before the first render so a crash-restart keeps lights.
    blend_path = out / spec.get("blend_name", "scene.blend")
    bpy.ops.wm.save_as_mainfile(filepath=str(blend_path))
    metrics["blend_path"] = str(blend_path)
    metrics["blend_bytes"] = blend_path.stat().st_size if blend_path.is_file() else 0

    for i, view in enumerate(renders):
        loc = view.get("location", [6, -8, 3])
        target = view.get("target", [0, 6, 1.2])
        cam_obj.location = Vector(loc)
        direction = Vector(target) - cam_obj.location
        cam_obj.rotation_euler = direction.to_track_quat("-Z", "Y").to_euler()
        if "focal_length_mm" in view:
            cam_data.lens = float(view["focal_length_mm"])
        path = out / view.get("filename", f"view_{i:02d}.png")
        scene.render.filepath = str(path)
        bpy.ops.render.render(write_still=True)
        metrics["renders"].append({
            "path": str(path),
            "bytes": path.stat().st_size if path.is_file() else 0,
            "location": loc,
            "target": target,
            "engine": scene.render.engine,
            "samples": samples,
        })
        # Checkpoint after each beat so a mid-run crash keeps prior frames + lights.
        if i == 0 or i == len(renders) - 1:
            bpy.ops.wm.save_as_mainfile(filepath=str(blend_path))

metrics_path = out / "metrics.json"
metrics_path.write_text(json.dumps(metrics, indent=2, sort_keys=True), encoding="utf-8")
print("PROCEDURAL_EMIT_OK", metrics_path)
