# Auto-generated by blender_vision.procedural.emit — do not hand-edit.
import json
import math
import sys
from pathlib import Path

import bpy
from mathutils import Euler, Matrix, Vector

SPEC_PATH = Path(r"""/Users/scammermike/Downloads/visionmcp-authority-worktrees/visionmcp-v2/tools/blender-vision-mcp/sandbox/datacenter-film/assets/_emit_shell/emit_spec.json""")
spec = json.loads(SPEC_PATH.read_text(encoding="utf-8"))
out = Path(spec["output_dir"])
out.mkdir(parents=True, exist_ok=True)

# --factory-startup already gave us a clean scene; do not re-read home file
# (read_factory_settings can re-trigger Metal GPU init crashes on some hosts).
scene = bpy.context.scene
scene.unit_settings.system = "METRIC"
scene.unit_settings.scale_length = 1.0
for obj in list(bpy.data.objects):
    bpy.data.objects.remove(obj, do_unlink=True)


def ensure_collection(name, parent=None):
    col = bpy.data.collections.get(name)
    if col is None:
        col = bpy.data.collections.new(name)
        if parent is None:
            scene.collection.children.link(col)
        else:
            parent.children.link(col)
    return col


def ensure_material(name):
    mat = bpy.data.materials.get(name)
    if mat is None:
        mat = bpy.data.materials.new(name=name)
        mat.use_nodes = True
        nodes = mat.node_tree.nodes
        bsdf = nodes.get("Principled BSDF")
        if bsdf:
            # Neutral placeholder; inverse-materials subsystem owns real shading.
            colour = {
                "steel": (0.35, 0.37, 0.40, 1),
                "chassis": (0.18, 0.18, 0.20, 1),
                "bezel": (0.12, 0.12, 0.13, 1),
                "vent": (0.08, 0.08, 0.09, 1),
                "metal": (0.55, 0.55, 0.58, 1),
                "drive": (0.22, 0.22, 0.25, 1),
                "gpu": (0.15, 0.25, 0.18, 1),
                "heatsink": (0.45, 0.45, 0.48, 1),
                "connector": (0.05, 0.05, 0.05, 1),
                "led": (0.1, 0.8, 0.2, 1),
                "port": (0.4, 0.55, 0.2, 1),
                "fan": (0.1, 0.1, 0.1, 1),
                "blanking": (0.2, 0.2, 0.22, 1),
                "pdu": (0.1, 0.15, 0.35, 1),
                "outlet": (0.7, 0.7, 0.75, 1),
                "breaker": (0.6, 0.15, 0.1, 1),
                "tray": (0.4, 0.35, 0.2, 1),
                "cable": (0.05, 0.05, 0.05, 1),
                "cooling": (0.7, 0.75, 0.8, 1),
                "louvre": (0.55, 0.6, 0.65, 1),
                "floor": (0.3, 0.3, 0.32, 1),
                "ceiling": (0.85, 0.85, 0.88, 1),
                "grid": (0.5, 0.5, 0.52, 1),
                "wall": (0.75, 0.75, 0.78, 1),
                "concrete": (0.55, 0.55, 0.55, 1),
                "threshold": (0.4, 0.35, 0.3, 1),
                "door": (0.25, 0.28, 0.35, 1),
                "aisle_cold": (0.2, 0.35, 0.55, 1),
                "aisle_hot": (0.55, 0.25, 0.2, 1),
                "guide": (0.9, 0.85, 0.2, 1),
                "volume": (0.5, 0.5, 0.5, 1),
                "junction": (0.35, 0.35, 0.38, 1),
                "structure": (0.45, 0.45, 0.45, 1),
                "containment": (0.6, 0.65, 0.7, 1),
                "glass": (0.7, 0.85, 0.9, 1),
                "seal": (0.1, 0.1, 0.1, 1),
                "panel": (0.3, 0.3, 0.32, 1),
                "baseboard": (0.4, 0.4, 0.42, 1),
                "cornice": (0.7, 0.7, 0.72, 1),
                "status_ok": (0.1, 0.9, 0.2, 1),
                "status_warn": (0.95, 0.75, 0.1, 1),
                "status_fault": (0.95, 0.15, 0.1, 1),
                "status_off": (0.15, 0.15, 0.15, 1),
                "status_maintenance": (0.2, 0.4, 0.9, 1),
                "status_cell": (0.2, 0.8, 0.3, 1),
                "neutral": (0.5, 0.5, 0.5, 1),
            }.get(name, (0.5, 0.5, 0.5, 1))
            bsdf.inputs["Base Color"].default_value = colour
            if name.startswith("status_") or name == "led":
                bsdf.inputs["Emission Color"].default_value = colour
                if "Emission Strength" in bsdf.inputs:
                    bsdf.inputs["Emission Strength"].default_value = 3.0
    return mat


def link_object(obj, collection):
    for col in list(obj.users_collection):
        col.objects.unlink(obj)
    collection.objects.link(obj)


def apply_transform(obj, transform):
    loc = transform.get("location", [0, 0, 0])
    rot = transform.get("rotation_euler", [0, 0, 0])
    scale = transform.get("scale", [1, 1, 1])
    obj.location = Vector(loc)
    obj.rotation_euler = Euler(rot, "XYZ")
    obj.scale = Vector(scale)


def make_box(name, size, collection, material):
    bpy.ops.mesh.primitive_cube_add(size=1.0, location=(0, 0, 0))
    obj = bpy.context.active_object
    obj.name = name
    obj.data.name = name + "_mesh"
    obj.scale = Vector(size)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    if material:
        obj.data.materials.append(ensure_material(material))
    link_object(obj, collection)
    return obj


def make_cylinder(name, size, segments, collection, material):
    # size = (diameter_x, diameter_y, height_z) in local space before object transform
    radius = 0.5 * max(size[0], size[1])
    depth = size[2]
    bpy.ops.mesh.primitive_cylinder_add(
        vertices=max(8, int(segments)),
        radius=radius,
        depth=depth,
        location=(0, 0, 0),
    )
    obj = bpy.context.active_object
    obj.name = name
    obj.data.name = name + "_mesh"
    if material:
        obj.data.materials.append(ensure_material(material))
    link_object(obj, collection)
    return obj


def make_hollow_box(name, size, wall, open_face, collection, material):
    # Outer box minus inner (approx via solidify on open box shell using 5 faces as boxes)
    sx, sy, sz = size
    t = max(wall, 0.001)
    parts = []
    # +X -X walls
    for sign, label in ((1, "px"), (-1, "nx")):
        if open_face in (f"{'+' if sign>0 else '-'}X",):
            continue
        o = make_box(f"{name}_{label}", (t, sy, sz), collection, material)
        o.data.transform(Matrix.Translation((sign * (sx * 0.5 - t * 0.5), 0.0, 0.0)))
        parts.append(o)
    for sign, label in ((1, "py"), (-1, "ny")):
        if open_face in (f"{'+' if sign>0 else '-'}Y",):
            continue
        o = make_box(f"{name}_{label}", (sx, t, sz), collection, material)
        o.data.transform(Matrix.Translation((0.0, sign * (sy * 0.5 - t * 0.5), 0.0)))
        parts.append(o)
    for sign, label in ((1, "pz"), (-1, "nz")):
        if open_face in (f"{'+' if sign>0 else '-'}Z",):
            continue
        o = make_box(f"{name}_{label}", (sx, sy, t), collection, material)
        o.data.transform(Matrix.Translation((0.0, 0.0, sign * (sz * 0.5 - t * 0.5))))
        parts.append(o)
    if not parts:
        return make_box(name, size, collection, material)
    # Join walls into one object with semantic name
    bpy.ops.object.select_all(action="DESELECT")
    for o in parts:
        o.select_set(True)
    bpy.context.view_layer.objects.active = parts[0]
    bpy.ops.object.join()
    obj = bpy.context.active_object
    obj.name = name
    obj.data.name = name + "_mesh"
    return obj


def make_vent_field(name, geom, collection, material):
    sx, sy, sz = geom["size"]
    cx = max(1, int(geom.get("count_x", 1)))
    cz = max(1, int(geom.get("count_z", 1)))
    pitch = geom.get("pitch", [sx / cx, 0.0, sz / cz])
    cell = geom.get("cell_size", [pitch[0] * 0.5, sy, pitch[2] * 0.5])
    parts = []
    for iz in range(cz):
        for ix in range(cx):
            x = (ix - (cx - 1) * 0.5) * pitch[0]
            z = (iz - (cz - 1) * 0.5) * pitch[2]
            o = make_box(f"{name}_{ix}_{iz}", cell, collection, material)
            # Offset the mesh data, not the object. join() adopts the first
            # object's origin, so moving objects here would put the joined
            # origin on a corner cell and the part transform would be applied
            # relative to that instead of to the field centre.
            o.data.transform(Matrix.Translation((x, 0.0, z)))
            parts.append(o)
    if not parts:
        return make_box(name, geom["size"], collection, material)
    bpy.ops.object.select_all(action="DESELECT")
    for o in parts:
        o.select_set(True)
    bpy.context.view_layer.objects.active = parts[0]
    bpy.ops.object.join()
    obj = bpy.context.active_object
    obj.name = name
    obj.data.name = name + "_mesh"
    return obj


def make_light_cell(name, geom, collection, material):
    return make_box(name, geom["size"], collection, material)


def make_bundle(name, geom, collection, material):
    # Multi-strand cylinder approximation along local Z
    strands = max(1, int(geom.get("count_x", geom.get("extras", {}).get("strand_count", 6))))
    dia = max(geom["size"][0], geom["size"][1])
    length = geom["size"][2]
    core_r = dia * 0.5
    strand_r = core_r / max(2.5, math.sqrt(strands))
    parts = []
    for i in range(strands):
        ang = 2 * math.pi * i / strands
        r = core_r * 0.45
        bpy.ops.mesh.primitive_cylinder_add(
            vertices=8,
            radius=strand_r,
            depth=length,
            location=(0.0, 0.0, 0.0),
        )
        o = bpy.context.active_object
        o.name = f"{name}_s{i}"
        # Mesh-data offset, not object location: join() adopts the first
        # strand's origin, which would shift the whole bundle.
        o.data.transform(Matrix.Translation((math.cos(ang) * r, math.sin(ang) * r, 0.0)))
        if material:
            o.data.materials.append(ensure_material(material))
        link_object(o, collection)
        parts.append(o)
    bpy.ops.object.select_all(action="DESELECT")
    for o in parts:
        o.select_set(True)
    bpy.context.view_layer.objects.active = parts[0]
    bpy.ops.object.join()
    obj = bpy.context.active_object
    obj.name = name
    obj.data.name = name + "_mesh"
    return obj


def build_geometry(name, geom, collection, material):
    kind = geom["kind"]
    if kind == "box" or kind == "panel":
        return make_box(name, geom["size"], collection, material)
    if kind == "cylinder":
        return make_cylinder(name, geom["size"], geom.get("segments", 12), collection, material)
    if kind == "hollow_box":
        return make_hollow_box(
            name, geom["size"], geom.get("wall_thickness", 0.002),
            geom.get("open_face", ""), collection, material,
        )
    if kind == "vent_field":
        return make_vent_field(name, geom, collection, material)
    if kind == "light_cell":
        return make_light_cell(name, geom, collection, material)
    if kind == "bundle" or kind == "tube":
        return make_bundle(name, geom, collection, material)
    return make_box(name, geom["size"], collection, material)


def build_part_tree(part, collection, parent_empty=None):
    geom = part["geometry"]
    obj = build_geometry(part["name"], geom, collection, part.get("material_slot", "neutral"))
    apply_transform(obj, part.get("transform", {}))
    if parent_empty is not None:
        obj.parent = parent_empty
    # State as custom properties (non-geometric)
    for key in part.get("state_keys", []):
        obj[key] = part.get("material_slot", "")
    children_root = obj
    for child in part.get("children", []):
        build_part_tree(child, collection, parent_empty=children_root)
    return obj


def triangle_count(objects):
    total = 0
    for obj in objects:
        if obj.type != "MESH" or obj.data is None:
            continue
        mesh = obj.data
        mesh.calc_loop_triangles()
        total += len(mesh.loop_triangles)
    return total


def world_bbox(objects):
    # Measure evaluated vertices, not obj.bound_box. bound_box is a cached,
    # pre-modifier value that is stale until the depsgraph catches up, which
    # reported this rack 10 mm taller than the geometry actually was.
    bpy.context.view_layer.update()
    depsgraph = bpy.context.evaluated_depsgraph_get()
    mins = Vector((1e9, 1e9, 1e9))
    maxs = Vector((-1e9, -1e9, -1e9))
    any_mesh = False
    for obj in objects:
        if obj.type != "MESH":
            continue
        evaluated = obj.evaluated_get(depsgraph)
        mesh = evaluated.to_mesh()
        try:
            if not mesh.vertices:
                continue
            any_mesh = True
            matrix = evaluated.matrix_world
            for vertex in mesh.vertices:
                w = matrix @ vertex.co
                mins.x = min(mins.x, w.x); mins.y = min(mins.y, w.y); mins.z = min(mins.z, w.z)
                maxs.x = max(maxs.x, w.x); maxs.y = max(maxs.y, w.y); maxs.z = max(maxs.z, w.z)
        finally:
            evaluated.to_mesh_clear()
    if not any_mesh:
        return [0, 0, 0], [0, 0, 0]
    return list(mins), list(maxs)


metrics = {"prototypes": {}, "instances": 0, "unique_meshes": 0, "renders": []}

# ---- Prototypes (one collection each, mesh data created once) ----
root_col = ensure_collection("ProceduralRoot")
proto_root = ensure_collection("Prototypes", root_col)
instance_root = ensure_collection("Instances", root_col)

prototype_collections = {}
for proto in spec.get("prototypes", []):
    pid = proto["prototype_id"]
    pcol = ensure_collection(pid, proto_root)
    pcol.hide_render = True
    pcol.hide_viewport = True
    for part in proto.get("parts", []):
        build_part_tree(part, pcol)
    objs = [o for o in pcol.objects]
    mins, maxs = world_bbox(objs)
    metrics["prototypes"][pid] = {
        "archetype": proto.get("archetype"),
        "lod": proto.get("lod", "near"),
        "triangle_count": triangle_count(objs),
        "bbox_min": mins,
        "bbox_max": maxs,
        "bbox_size": [maxs[i] - mins[i] for i in range(3)],
        "object_count": len(objs),
        "part_names": [o.name for o in objs],
    }
    prototype_collections[pid] = pcol

metrics["unique_meshes"] = len(prototype_collections)

# ---- Instances as collection instances (linked, not copies) ----
for placement in spec.get("placements", []):
    pid = placement["prototype_id"]
    pcol = prototype_collections.get(pid)
    if pcol is None:
        continue
    inst = bpy.data.objects.new(placement["instance_id"], None)
    inst.instance_type = "COLLECTION"
    inst.instance_collection = pcol
    apply_transform(inst, {
        "location": placement.get("location", [0, 0, 0]),
        "rotation_euler": placement.get("rotation_euler", [0, 0, 0]),
        "scale": placement.get("scale", [1, 1, 1]),
    })
    for k, v in placement.get("state", {}).items():
        inst[k] = v
    link_object(inst, instance_root)
    metrics["instances"] += 1

# Unhide instance root; keep prototypes hidden (instances still draw them)
for pcol in prototype_collections.values():
    pcol.hide_viewport = False  # required for collection instances to draw
    pcol.hide_render = False

# ---- Optional standalone archetype metrics (no placements) ----
for entry in spec.get("archetype_builds", []):
    name = entry["name"]
    lod = entry.get("lod", "near")
    acol = ensure_collection(f"arch_{name}_{lod}", root_col)
    for part in entry.get("parts", []):
        build_part_tree(part, acol)
    objs = [o for o in acol.objects]
    mins, maxs = world_bbox(objs)
    metrics.setdefault("archetypes", {})[f"{name}:{lod}"] = {
        "triangle_count": triangle_count(objs),
        "bbox_min": mins,
        "bbox_max": maxs,
        "bbox_size": [maxs[i] - mins[i] for i in range(3)],
        "object_count": len(objs),
        "part_names": sorted({o.name for o in objs}),
    }

# ---- Save .blend ----
blend_path = out / spec.get("blend_name", "scene.blend")
bpy.ops.wm.save_as_mainfile(filepath=str(blend_path))
metrics["blend_path"] = str(blend_path)
metrics["blend_bytes"] = blend_path.stat().st_size

# ---- Export GLB ----
glb_path = out / spec.get("glb_name", "scene.glb")
# Select all mesh-bearing content for export
bpy.ops.object.select_all(action="SELECT")
bpy.ops.export_scene.gltf(
    filepath=str(glb_path),
    export_format="GLB",
    use_selection=False,
    export_apply=False,
)
metrics["glb_path"] = str(glb_path)
metrics["glb_bytes"] = glb_path.stat().st_size if glb_path.is_file() else 0

# ---- Renders ----
renders = spec.get("renders") or []
if renders:
    # Simple world lighting
    world = bpy.data.worlds.new("World")
    scene.world = world
    world.use_nodes = True
    bg = world.node_tree.nodes["Background"]
    bg.inputs[0].default_value = (0.05, 0.06, 0.08, 1)
    bg.inputs[1].default_value = 0.4

    # Key light
    bpy.ops.object.light_add(type="AREA", location=(4, -6, 5))
    key = bpy.context.active_object
    key.data.energy = 800
    key.data.size = 4

    bpy.ops.object.light_add(type="AREA", location=(-3, 4, 4))
    fill = bpy.context.active_object
    fill.data.energy = 250
    fill.data.size = 3

    scene.render.engine = spec.get("render_engine", "BLENDER_EEVEE_NEXT")
    # Fall back for Blender 4.2 naming
    engines = bpy.types.RenderSettings.bl_rna.properties["engine"].enum_items.keys()
    if scene.render.engine not in engines:
        scene.render.engine = "BLENDER_EEVEE"
    scene.render.resolution_x = int(spec.get("resolution", [1280, 720])[0])
    scene.render.resolution_y = int(spec.get("resolution", [1280, 720])[1])
    scene.render.filepath = str(out / "render_")
    scene.render.image_settings.file_format = "PNG"

    cam_data = bpy.data.cameras.new("PreviewCam")
    cam_obj = bpy.data.objects.new("PreviewCam", cam_data)
    scene.collection.objects.link(cam_obj)
    scene.camera = cam_obj
    cam_data.lens = 35

    for i, view in enumerate(renders):
        loc = view.get("location", [6, -8, 3])
        target = view.get("target", [0, 6, 1.2])
        cam_obj.location = Vector(loc)
        direction = Vector(target) - cam_obj.location
        cam_obj.rotation_euler = direction.to_track_quat("-Z", "Y").to_euler()
        path = out / view.get("filename", f"view_{i:02d}.png")
        scene.render.filepath = str(path)
        bpy.ops.render.render(write_still=True)
        metrics["renders"].append({
            "path": str(path),
            "bytes": path.stat().st_size if path.is_file() else 0,
            "location": loc,
            "target": target,
        })

metrics_path = out / "metrics.json"
metrics_path.write_text(json.dumps(metrics, indent=2, sort_keys=True), encoding="utf-8")
print("PROCEDURAL_EMIT_OK", metrics_path)
